# Site settings
title: Sanitaris per la Independència
logo: "assets/logo-1028x214.png"
email: adhesions@sanitarisxindependencia.cat
description: > # this means to ignore newlines until "baseurl:"
  Sanitaris per la Independència
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sanitarisxindependencia.cat" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
