# Site settings
title: Sanitaris per la Independència
logo: "assets/logo-1028x214.png"
email: adhesions@sanitarisxindependencia.cat
description: > # this means to ignore newlines until "baseurl:"
  Sanitaris per la Independència
baseurl: "" # the subpath of your site, e.g. /blog/
#baseurl: "/sanitaris-per-la-independencia/"
url: "http://sanitarisxindependencia.cat" # the base hostname & protocol for your site

#Exclude from Build
exclude: ['bin', 'Gemfile', 'Gemfile.lock', 'bower.json', 'feed.xml', 'jekyll-multiple-languages-plugin']

# Build settings
markdown: kramdown

# Dependencies
# Using Gemfile seemed to work better than defining gems here
# gems: [jekyll-multiple-languages-plugin]

# i18n
# Using Jekyll Multiple Languages Plugin:
# https://github.com/screeninteraction/jekyll-multiple-languages-plugin
languages: ["ca", "es"]
exclude_from_localizations: ["assets", "css"]
